import { randomBytes, randomInt } from 'node:crypto';
import { existsSync, writeFileSync, chmodSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Writes .env.production with freshly generated secrets.
 *
 * Exists because "generate four unrelated secrets and paste them into the right
 * lines" is the step people get wrong - by reusing one value, by pasting a
 * newline into the middle, or by leaving a placeholder in and only finding out
 * when the server refuses to boot.
 *
 *   node scripts/generate-env.mjs --domain chitchak.example --email me@example.com
 */

const args = new Map();
for (let i = 2; i < process.argv.length; i += 2) {
  const key = process.argv[i]?.replace(/^--/, '');
  if (key) args.set(key, process.argv[i + 1] ?? '');
}

const domain = args.get('domain');
const email = args.get('email');
const force = process.argv.includes('--force');

if (!domain || !email) {
  console.error(`Usage:
  node scripts/generate-env.mjs --domain <yourdomain.com> --email <you@example.com> [--signup-code <code>] [--force]

  --domain       the domain you own, with no subdomain. The stack serves
                 api.<domain> and sfu.<domain> beneath it.
  --email        where Let's Encrypt sends certificate expiry warnings.
  --signup-code  the code friends type when registering. One is generated if
                 you do not supply it. Pass "none" to allow open registration.
  --force        overwrite an existing .env.production.`);
  process.exit(1);
}

if (!/^[a-z0-9-]+(\.[a-z0-9-]+)+$/i.test(domain)) {
  console.error(`"${domain}" does not look like a domain. Give it without a subdomain, e.g. chitchak.example`);
  process.exit(1);
}
if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
  console.error(`"${email}" does not look like an email address.`);
  process.exit(1);
}

const repoRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(repoRoot, '.env.production');

if (existsSync(target) && !force) {
  console.error(
    `.env.production already exists.\n\n` +
      `Refusing to overwrite it: regenerating JWT_SECRET signs everyone out, and a new\n` +
      `POSTGRES_PASSWORD locks the server out of its own database. Pass --force only if\n` +
      `you mean it.`,
  );
  process.exit(1);
}

/** URL-safe, no padding, so it cannot break a shell or a YAML value. */
const secret = () => randomBytes(36).toString('base64url');

// A code people will read out loud to each other, so words rather than noise.
const ADJECTIVES = ['brass', 'amber', 'quiet', 'north', 'rapid', 'silver', 'copper', 'plain'];
const NOUNS = ['otter', 'harbour', 'lantern', 'meadow', 'anchor', 'falcon', 'cinder', 'willow'];
const pick = (list) => list[randomInt(0, list.length)];

const supplied = args.get('signup-code');
const signupCode =
  supplied === 'none' ? '' : (supplied ?? `${pick(ADJECTIVES)}-${pick(NOUNS)}-${randomInt(1000, 9999)}`);

const contents = `# Generated by scripts/generate-env.mjs on ${new Date().toISOString()}
# Everything below is a secret. Do not commit this file.

CHITCHAK_DOMAIN=${domain}
ACME_EMAIL=${email}

POSTGRES_PASSWORD=${secret()}
JWT_SECRET=${secret()}

LIVEKIT_API_KEY=chitchak
LIVEKIT_API_SECRET=${secret()}

# Friends type this once when they register. Empty means anyone who finds the
# server can create an account.
SIGNUP_CODE=${signupCode}
`;

writeFileSync(target, contents, { mode: 0o600 });
try {
  chmodSync(target, 0o600);
} catch {
  // Windows has no POSIX modes; harmless, and the file is only ever generated
  // for real on the server.
}

console.log(`Wrote ${target}

  Domain       ${domain}   ->  api.${domain} and sfu.${domain}
  Signup code  ${signupCode || '(none - registration is open)'}

Next:
  1. Point A records for api.${domain} and sfu.${domain} at this server.
  2. docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build
  3. docker compose -f docker-compose.prod.yml --env-file .env.production --profile tools run --rm migrate

Keep this file. Regenerating JWT_SECRET signs everyone out; regenerating
POSTGRES_PASSWORD locks the server out of its own database.`);
