#!/usr/bin/env bash
#
# One-shot server preparation for ChitChak.
#
# Installs Docker, opens the firewall, writes .env.production with fresh
# secrets, and brings the stack up. Safe to re-run: every step checks whether it
# has already been done.
#
#   sudo bash scripts/server-setup.sh --domain yourdomain.com --email you@example.com
#
# Deliberately written in bash rather than Node so it has no prerequisites
# beyond a fresh Ubuntu or Debian install.

set -euo pipefail

DOMAIN=""
EMAIL=""
SIGNUP_CODE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --email) EMAIL="${2:-}"; shift 2 ;;
    --signup-code) SIGNUP_CODE="${2:-}"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$DOMAIN" || -z "$EMAIL" ]]; then
  cat >&2 <<'USAGE'
Usage:
  sudo bash scripts/server-setup.sh --domain <yourdomain.com> --email <you@example.com> [--signup-code <code>]

  --domain       the domain you own, with no subdomain. Serves api.<domain> and sfu.<domain>.
  --email        where Let's Encrypt sends certificate expiry warnings.
  --signup-code  what friends type when registering. Generated if omitted.
USAGE
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "Run this with sudo - it installs packages and edits the firewall." >&2
  exit 1
fi

if [[ ! -f docker-compose.prod.yml ]]; then
  echo "Run this from inside the cloned repository (the folder holding docker-compose.prod.yml)." >&2
  exit 1
fi

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# --- Docker -----------------------------------------------------------------

if command -v docker >/dev/null 2>&1; then
  say "Docker is already installed"
else
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi

# --- Firewall ---------------------------------------------------------------
#
# UDP 7882 is the one that matters. Without it, calls connect and carry no
# audio, which looks like a bug in the app rather than a closed port.

say "Opening firewall ports"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp   >/dev/null
  ufw allow 80/tcp   >/dev/null
  ufw allow 443/tcp  >/dev/null
  ufw allow 7881/tcp >/dev/null
  ufw allow 7882/udp >/dev/null
  ufw allow 3478/udp >/dev/null
  ufw --force enable >/dev/null
  echo "    22, 80, 443, 7881/tcp, 7882/udp, 3478/udp allowed"
else
  echo "    ufw not installed; skipping. Make sure those ports are open by other means."
fi

cat <<'PANEL'

    Check your hosting control panel as well. Many providers run a second
    firewall there that ufw cannot see, and it usually blocks everything
    except 22, 80 and 443 by default.

PANEL

# --- Secrets ----------------------------------------------------------------

if [[ -f .env.production ]]; then
  say "Keeping the existing .env.production"
  echo "    Not regenerating: a new JWT_SECRET signs everyone out, and a new"
  echo "    POSTGRES_PASSWORD locks the server out of its own database."
else
  say "Generating secrets"
  gen() { openssl rand -base64 36 | tr -d '\n=+/' | cut -c1-44; }

  if [[ -z "$SIGNUP_CODE" ]]; then
    ADJ=(brass amber quiet north rapid silver copper plain)
    NOUN=(otter harbour lantern meadow anchor falcon cinder willow)
    SIGNUP_CODE="${ADJ[$RANDOM % 8]}-${NOUN[$RANDOM % 8]}-$((RANDOM % 9000 + 1000))"
  fi

  cat > .env.production <<EOF
# Generated by scripts/server-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Everything below is a secret. Do not commit this file.

CHITCHAK_DOMAIN=${DOMAIN}
ACME_EMAIL=${EMAIL}

POSTGRES_PASSWORD=$(gen)
JWT_SECRET=$(gen)

LIVEKIT_API_KEY=chitchak
LIVEKIT_API_SECRET=$(gen)

SIGNUP_CODE=${SIGNUP_CODE}
EOF
  chmod 600 .env.production
  echo "    Written to .env.production (readable only by root)"
fi

# --- DNS sanity check -------------------------------------------------------
#
# Caddy cannot get a certificate before these resolve, and "stuck getting a
# certificate" is a far more confusing symptom than being told up front.

say "Checking DNS"
PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || echo '')"
DNS_OK=1
for host in "api.${DOMAIN}" "sfu.${DOMAIN}"; do
  RESOLVED="$(getent hosts "$host" 2>/dev/null | awk '{print $1}' | head -n1 || true)"
  if [[ -z "$RESOLVED" ]]; then
    echo "    $host does not resolve yet"
    DNS_OK=0
  elif [[ -n "$PUBLIC_IP" && "$RESOLVED" != "$PUBLIC_IP" ]]; then
    echo "    $host resolves to $RESOLVED, but this server is $PUBLIC_IP"
    DNS_OK=0
  else
    echo "    $host -> $RESOLVED"
  fi
done

if [[ $DNS_OK -eq 0 ]]; then
  cat <<EOF

    DNS is not ready. Add these A records at your registrar, then re-run:

        api.${DOMAIN}   ->  ${PUBLIC_IP:-this server's IP}
        sfu.${DOMAIN}   ->  ${PUBLIC_IP:-this server's IP}

    Propagation is usually minutes but can take hours. Everything else above
    is done and will not be repeated.
EOF
  exit 1
fi

# --- Start ------------------------------------------------------------------

say "Building and starting (first run pulls images and compiles; give it a few minutes)"
docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build

say "Applying database migrations"
docker compose -f docker-compose.prod.yml --env-file .env.production \
  --profile tools run --rm migrate

say "Waiting for the API to answer"
for _ in $(seq 1 30); do
  if curl -fsS --max-time 5 "https://api.${DOMAIN}/health" >/dev/null 2>&1; then
    break
  fi
  sleep 5
done

CODE="$(grep '^SIGNUP_CODE=' .env.production | cut -d= -f2-)"

cat <<EOF

────────────────────────────────────────────────────────────
 Done.

   API           https://api.${DOMAIN}
   SFU           wss://sfu.${DOMAIN}
   Signup code   ${CODE:-(none - registration is open)}

 Check it:       curl https://api.${DOMAIN}/health
 Watch logs:     docker compose -f docker-compose.prod.yml --env-file .env.production logs -f

 Next, on your own PC, build the installer with this domain baked in:

   cd apps/desktop
   cp .env.production.example .env.production
   # replace example.com with ${DOMAIN} in all three values
   npm run dist:win

 If the certificate is still pending, give Caddy a minute and check the logs.
────────────────────────────────────────────────────────────
EOF
